from concurrent.futures import ProcessPoolExecutor, as_completed
from curses import init_pair
from itertools import product
import logging
from pathlib import Path
import json

import numpy as np
from typing import List, Dict
import pandas as pd
from tqdm import tqdm
from findiff import Diff

from llmode.equation import Equation
from llmode.island import Island
from llmode.llm import Llm
from llmode.program import Program
from llmode.system import System
from llmode.llm import generate_prompt
from llmode.utils import refine_generated_hypothesis, compute_pareto_frontier

def evaluate_system(
        system_str: str,
        init_train: np.ndarray,
        time_stamps_train_val: np.ndarray,
        trajectory_train_val: np.ndarray,
        init_test: np.ndarray,
        time_stamps_test: np.ndarray,
        trajectory_test: np.ndarray) -> Dict:

        system = System(system_str)
        try:
            predicted_trajectory_train_val = system.evaluate_trajectory(init_train, time_stamps_train_val)
            mse_train_val = np.mean((predicted_trajectory_train_val - trajectory_train_val) ** 2)
            predicted_trajectory_test = system.evaluate_trajectory(init_test, time_stamps_test)
            mse_test = np.mean((predicted_trajectory_test - trajectory_test) ** 2)
            nmse_test = np.mean((predicted_trajectory_test - trajectory_test) ** 2) / np.mean(trajectory_test ** 2)
        except Exception as e:
            mse_train_val = np.nan
            mse_test = np.nan
            nmse_test = np.nan
            logging.warning(f"Error evaluating system {system}: {e}")
        result = {
            'complexity': system.complexity(),
            'mse_train_val': mse_train_val,
            'mse_test': mse_test,
            'nmse_test': nmse_test,
            'system_str': system.to_string(),
        }
        return result

def validate_hypothesis(
        island_id: int,
        hypothesis: str,
        n_variables: int,
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: np.ndarray,
        y_val: np.ndarray,
    ) -> Dict:
    result = {
        'island_id': island_id,
        'equation_str': None,
        'mse_train': None,
    }
    try:
        if ('j' in hypothesis) or ('I' in hypothesis):
            return result
        equation = Equation(hypothesis, all_variables=[f"x_{i}" for i in range(n_variables)])
        equation.optimize_coefficients(X_train, y_train)
        if 'I' in equation.to_string():
            return result
        predicted_derivative = equation(X_train)
        mse_train = np.mean((y_train - predicted_derivative) ** 2)
        result['equation_str'] = equation.to_string(precision=20)
        result['mse_train'] = mse_train
    except Exception as e:
        pass
    return result

class LlmOdeEquation:
    '''Eeach equation evloves separately in the LlmOde. Each equation consits of independent islands.'''
    def __init__(self, llm: Llm,
                 t_train: np.ndarray, # (n_samples, )
                 X_train: np.ndarray, # (n_samples, n_variables)
                 y_train: np.ndarray, # (n_samples, )
                 t_val: np.ndarray, # (n_samples, )
                 X_val: np.ndarray, # (n_samples, n_variables)
                 y_val: np.ndarray, # (n_samples, )
                 pareto_level_file: Path,
                 config: Dict):
        '''
        Args:
            llm: LLM model
            t_train: time stamps for the training data
            X_train: training data
            y_train: training labels
            t_val: time stamps for the validation data
            X_val: validation data
            y_val: validation labels
            pareto_level_file: path to the pareto level file
            config: configuration dictionary
                - n_islands: number of islands. Default is 4.
                - island_size: number of programs in each island. Default is 2.
                - k: number of in-context examples. Default is 8.
                - b: number of hypothesis generated by the LLM. Default is 3.
                - iters_per_refine: number of iterations per refine (trim and mixing). Default is 5.
                - num_mixing: number of programs to mix between islands. Default is 2.
        '''
        self.llm = llm
        self.X_train = X_train
        self.y_train = y_train
        self.X_val = X_val
        self.y_val = y_val
        self.pareto_level_file = pareto_level_file
        self.n_variables = self.X_train.shape[1] # number of equations in the system

        self.n_islands = config.get('n_islands', 4)
        self.island_size = config.get('island_size', 2)
        self.k = config.get('k', 8)
        self.b = config.get('b', 3)
        self.iters_per_refine = config.get('iters_per_refine', 5)
        self.num_mixing = config.get('num_mixing', 2)

        self.complexity_pf = pd.DataFrame(columns=['complexity', 'mse_val', 'program'])
        self.iteration = 0
        self.seen_programs = set() # programs that have been seen during the training
        # initialize islands
        self.islands = [Island(island_size=self.island_size,
                               X=self.X_train,
                               y=self.y_train) for _ in range(self.n_islands)]

    def _evolve_islands(self) -> List[Island]:
        '''
        Evolve the islands for one iteration/step.
        '''

        # prompt the llm to generate hypothesis for each island
        prompts = []
        sampled_programs = []
        for island in self.islands:
            programs = island.sample_programs(self.k)
            examples_str = [program.equation.get_skeleton() for program in programs]
            prompt = generate_prompt(examples_str, n_new=self.b, n_variables=self.n_variables)
            prompts.append(prompt)
            sampled_programs.append(programs)
        responses = self.llm.query(prompts)

        # refine the generated hypothesis
        all_hypothesis = []
        for prompt_id in range(len(prompts)):
            hypothesis = responses[prompt_id].split('\n')[:self.b]
            hypothesis = list(map(refine_generated_hypothesis, hypothesis))
            all_hypothesis.append(hypothesis)

        # optimize the coefficients of the generated hypothesis and add to the islands
        inputs = [
            (island_id, hypothesis, self.n_variables, self.X_train, self.y_train, self.X_val, self.y_val)
            for island_id in range(len(self.islands)) for hypothesis in all_hypothesis[island_id]
        ]
        with ProcessPoolExecutor(max_workers=12) as executor:
            futures = [
                executor.submit(validate_hypothesis, *input_) for input_ in inputs
            ]
            validated_hypothesis = [future.result() for future in as_completed(futures)]
        for validated_hypothesis in validated_hypothesis:
            if (validated_hypothesis['equation_str'] is not None) and (not np.isnan(validated_hypothesis['mse_train'])) and (not np.isinf(validated_hypothesis['mse_train'])):
                island = self.islands[validated_hypothesis['island_id']]
                program = Program(equation=Equation(validated_hypothesis['equation_str'], all_variables=[f"x_{i}" for i in range(self.n_variables)]), score=validated_hypothesis['mse_train'])
                island.add_program(program)

    def _refine_islands(self) -> List[Island]:
        '''
        Refine the islands by trimming low performing programs and mixing the islands.
        '''
        # trim low performing programs
        for island in self.islands:
            island.trim_programs_()

        # mix the islands
        for src_id, src_island in enumerate(self.islands):
            dst_id = src_id
            while dst_id == src_id:
                dst_id = np.random.randint(0, len(self.islands))
            dst_island = self.islands[dst_id]
            src_programs = src_island.sample_programs(self.num_mixing)
            dst_programs = dst_island.sample_programs(self.num_mixing)
            src_island.add_programs(dst_programs)
            dst_island.add_programs(src_programs)

    def _update_complexity_pareto_frontier(self):
        '''
        Update the complexity-performance Pareto frontier using the validation data.
        '''
        all_programs = [program for island in self.islands for program in island.get_programs()]
        new_programs = [program for program in all_programs if program not in self.seen_programs]
        self.seen_programs.update(new_programs)

        new_mse_vals = []
        complexities = []
        for program in new_programs:
            try:
                predicted_derivative = program.equation(self.X_val)
                mse_val = np.mean((predicted_derivative - self.y_val) ** 2)
            except Exception as e:
                logging.warning(f"Error evaluating validation derivative for program {program}: {e}")
                new_mse_vals.append(np.nan)
            finally:
                complexities.append(program.equation.complexity())
                new_mse_vals.append(mse_val)
        df = pd.DataFrame({'complexity': complexities, 'mse_val': new_mse_vals, 'program': new_programs})
        self.complexity_pf = pd.concat([self.complexity_pf, df])
        self.complexity_pf = self.complexity_pf.dropna().drop_duplicates().reset_index(drop=True)
        self.complexity_pf = compute_pareto_frontier(self.complexity_pf, ['complexity', 'mse_val'])

    def _log_complexity_pareto_frontier(self) -> None:
        for _, row in self.complexity_pf.iterrows():
            with open(self.pareto_level_file, 'a') as f:
                f.write(json.dumps({
                    'iteration': self.iteration,
                    'complexity': row['complexity'],
                    'mse_val': row['mse_val'],
                    'program': row['program'].to_json(),
                }) + '\n')

    def get_pareto_frontier(self) -> pd.DataFrame:
        '''
        Get the complexity-performance Pareto frontier.
        '''
        return self.complexity_pf

    def step(self):
        '''
        Evolve the islands for one iteration
        '''
        self._evolve_islands()
        self.iteration += 1
        if self.iteration % self.iters_per_refine == 0:
            self._refine_islands()
        self._update_complexity_pareto_frontier()
        self._log_complexity_pareto_frontier()
class LlmOde:
    def __init__(self, llm: Llm,
                 problem: Dict,
                 results_dir: Path,
                 config: Dict):
        '''
        Args:
            llm: LLM model
            problem: problem dictionary
                - name: problem name
                - equation: problem equation
                - init_train: initial training state
                - init_test: initial test state
            results_dir: path to the results directory
            config: configs for the LlmOdeEquation
        '''

        self.problem_name = problem['name']
        self.true_system = System(problem['equation'])
        self.init_train = problem['init_train']
        self.init_test = problem['init_test']
        self.results_dir = results_dir

        self.time_stamps_train = np.linspace(0, 5, 100)
        self.time_stamps_val = np.linspace(0, 5, 100)
        self.time_stamps_train_val = np.linspace(0, 10, 100)
        self.time_stamps_test = np.linspace(0, 10, 100)

        self.trajectory_train = self.true_system.evaluate_trajectory(self.init_train, self.time_stamps_train)
        self.trajectory_val = self.true_system.evaluate_trajectory(self.trajectory_train[-1], self.time_stamps_val)
        self.trajectory_train_val = self.true_system.evaluate_trajectory(self.init_train, self.time_stamps_train_val)
        self.trajectory_test = self.true_system.evaluate_trajectory(self.init_test, self.time_stamps_test)

        self.observed_derivative_train = Diff(0, self.time_stamps_train[1] - self.time_stamps_train[0], acc=4)(self.trajectory_train)
        self.observed_derivative_train_val = Diff(0, self.time_stamps_train_val[1] - self.time_stamps_train_val[0], acc=4)(self.trajectory_train_val)
        self.observed_derivative_val = Diff(0, self.time_stamps_val[1] - self.time_stamps_val[0], acc=4)(self.trajectory_val)

        self.n_variables = self.trajectory_train.shape[1]
        self.llmOdeEquations = []
        for i in range(self.n_variables):
            llmOdeEquation = LlmOdeEquation(llm=llm,
                                               t_train=self.time_stamps_train,
                                               X_train=self.trajectory_train,
                                               y_train=self.observed_derivative_train[:, i],
                                               t_val=self.time_stamps_val,
                                               X_val=self.trajectory_val,
                                               y_val=self.observed_derivative_val[:, i],
                                               pareto_level_file=self.results_dir / f'{self.problem_name}_variable_x{i}.complexity_pf.jsonl',
                                               config=config)
            self.llmOdeEquations.append(llmOdeEquation)

    def _store_results(self, filepath: Path):
        complexity_pfs = [x.get_pareto_frontier() for x in self.llmOdeEquations]
        equations_list = [pf['program'].apply(lambda x: x.equation).to_list() for pf in complexity_pfs]
        system_strs = [' | '.join(map(str, equations)) for equations in product(*equations_list)]
        system_perfs = []

        with ProcessPoolExecutor(max_workers=30) as executor:
            futures = [
                executor.submit(evaluate_system,
                                system_str,
                                self.init_train,
                                self.time_stamps_train_val,
                                self.trajectory_train_val,
                                self.init_test,
                                self.time_stamps_test,
                                self.trajectory_test) for system_str in system_strs]
            system_perfs = []
            for future in tqdm(as_completed(futures), total=len(futures)):
                system_perfs.append(future.result())


        system_perfs = pd.DataFrame(system_perfs)
        system_perfs = system_perfs.sort_values(by='mse_train_val')
        system_perfs.to_csv(filepath, index=False)

    def train(self, n_iterations: int, save_iterations: List[int]):
        '''
        Args:
            n_iterations: number of iterations
            save_iterations: iterations to save the complexity Pareto frontier and store the results
        '''
        for iteration in tqdm(range(1, n_iterations + 1), desc="Training"):
            for llmOdeEquation in self.llmOdeEquations:
                llmOdeEquation.step()
            if iteration in save_iterations or iteration == n_iterations:
                self._store_results(self.results_dir / f'{self.problem_name}_iteration_{iteration}.csv')
